name: Build and Publish Validator Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the code with submodules
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install dependencies
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev \
            libudev-dev \
            pkg-config \
            zlib1g-dev \
            llvm \
            clang \
            cmake \
            make \
            libprotobuf-dev \
            protobuf-compiler

      # Cache cargo dependencies
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo Index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      # Cache target directory
      - name: Cache Target Directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-

      # Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      # Build the validator binaries
      - name: Build Validator
        run: |
          mkdir -p /tmp/${{ github.ref_name }}
          ./scripts/cargo-install-all.sh --validator-only /tmp/${{ github.ref_name }}

      # Package the build output
      - name: Package Release
        run: |
          cd /tmp/${{ github.ref_name }}
          tar -czvf validator-release-${{ github.ref_name }}.tar.gz bin/
          mv validator-release-${{ github.ref_name }}.tar.gz $GITHUB_WORKSPACE/

      # Upload the artifact as a release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: validator-release-${{ github.ref_name }}.tar.gz
          asset_name: validator-release-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip